#! /usr/bin/env groovy
pipeline {
 agent any
 stages {
 stage('Build') {
 steps {
 
 sh '''
 cd /var/lib/jenkins/workspace/Deploy-SmartTools-React
sudo npm run build
sudo cp build/. /etc/nginx/html/
sudo cp -r build/. /etc/nginx/html/
sudo systemctl reload  nginx
 '''
       }
    }
  }
}
